### ISSUE TITLE
wrong APK at release 1.2?

### ISSUE THREAD

**Issue by IzzySoft** [aritra-tech/UnCrack#1]
The APK attached to release 1.2 identifies as

    package: name='com.geekymusketeers.uncrack' versionCode='1' versionName='1.0'

You're sure that's the correct one? I'd expect something like `versionCode='3' versionName='1.2'` given it's the 3rd release and named 1.2 (not increasing `versionCode` will make updates harder on the user).

**Comment by aritra-tech** [comment]
It's fixed now i guess @IzzySoft

**Comment by IzzySoft** [comment]
Is it? I just grabbed the APK from the latest release, it still says the same.

**Comment by aritra-tech** [comment]
Okay I will do the changes.

**Comment by IzzySoft** [comment]
As you just closed the issue: unless you've replaced the APK at the latest tag (or created a new one with the correctly versioned APK), my updater will complain on each run and I'll have to disable update check :wink:
