### ISSUE TITLE
Problems with Build

### ISSUE THREAD

**Issue by nvdavilam85** [aritra-tech/UnCrack#7]
Unresolved reference: SettingsItemBinding
Unresolved reference: text
Unresolved reference: databinding

import com.geekymusketeers.uncrack.databinding.SettingsItemBinding :  (SettingsItemBinding) not exists in project.

Could you help me with this file?

**Comment by aritra-tech** [comment]
Sorry for the late reply.
Can you please delete the previous project and clone it again?
Or first `Clean Project` from `Build` and then `Rebuild Project` again from `Build` after performing this it shall work fine.
